---
version: 0.2

phases:
  build:
    commands:
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install awscli
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - ls -al
      - yum -y install zip
      - curl -sL https://rpm.nodesource.com/setup_11.x | bash -
      - yum install -y --enablerepo=nodesource nodejs
      - cd web\ files
      - npm install --loglevel info --no-progress
      - cd ../
      - sed 's@LunarXP@'"$SITENAME"'@' web\ files/settings.json
      - sed 's@https://www.lunarxp.com/@'"$SITEURL"'@' web\ files/settings.json
      - sed 's@lunar-xp-logo.png@'"$LOGONAME"'@' web\ files/settings.json
      - sed 's@(800) 859-7656@'"$SITEPHONE"'@' web\ files/settings.json
      - sed 's@800 N. Magnolia Blvd.@'"$SITEADDRESS"'@' web\ files/settings.json
      - sed 's@Orlando@'"$SITECITY"'@' web\ files/settings.json
      - sed 's@FL@'"$SITESTATE"'@' web\ files/settings.json
      - sed 's@32803@'"$SITEPOSTAL"'@' web\ files/settings.json
      - sed 's@https://www.facebook.com/@'"$SITEFACEBOOK"'@' web\ files/settings.json
      - sed 's@https://twitter.com/@'"$SITETWITTER"'@' web\ files/settings.json
      - sed 's@https://www.linkedin.com/@'"$SITELINKEDIN"'@' web\ files/settings.json
      - sed 's@https://www.youtube.com/@'"$SITEYOUTUBE"'@' web\ files/settings.json
      - sed 's@https://www.instagram.com/@'"$SITEINSTAGRAM"'@' web\ files/settings.json
      - zip -r lunarxp.zip web\ files www config.json
      - aws s3 cp lunarxp.zip s3://solodev-aws-ha
      - git init
      - git config --global user.email "${GITEMAIL}"
      - git remote remove origin
      - git remote add origin https://${AUTH_STRING}@scott.org/${GITORG}/${REPO}.git
      - git config --global push.default simple
      - git fetch
      - git checkout master
      - git add lunarxp.zip
      - git commit -m "updating lunarxp.zip"
      - git push origin master
      - rm -Rf lunarxp.zip